export enum GAME_STATE {
    OPENING,
    WELCOME_TO_CITY,
    IN_CITY,
    MARKET,
    LEAVING,
    TRADE_PLAYERS,
    TRADING
}

export enum TRADING_STATE {
    WAITING,
    MANAGING,
    WAITING_FOR_RESPONSE,
    EVAL_TRADE,
    TRADE_ACCEPTED
}